[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Unity WebGL compressed assets are served correctly in production
[[headers]]
  for = "/Aerylect/Build/*.data.br"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Aerylect/Build/*.wasm.br"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Aerylect/Build/*.framework.js.br"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"

# In case Unity emitted other compressed JS files
[[headers]]
  for = "/Aerylect/Build/*.js.br"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"